spring:
    config:
        activate:
            on-profile: dev
server:
  port: 8000
---
spring:
    config:
        activate:
            on-profile: stage
server:
  port: 9000
---
server:
  servlet:
    context-path: /api
---
spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    url: jdbc:h2:mem:testdb
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: debug
